### ISSUE TITLE
Tiny IDs not unique across multiple tables

### ISSUE THREAD

**Issue by aranw** [zackkitzmiller/tiny-php#24]
I've added Tiny string IDs to a couple of my tables now and noticed it has the same string_ids for ids across multiple tables. 

Would it be perhaps a good idea to have the ability to attach an additional string to the set?

For example 
```
echo $tiny->to(15, 'additionalstuffhere');
\\ asAs2
echo $tiny->from('asAs2', 'additionalstuffhere');
\\ 15

echo $tiny->to(15, 'differenttexthere');
\\ p9hhh
echo $tiny->from('p9hhh', 'differenttexthere');
\\ 15
```

Thoughts?

**Comment by zackkitzmiller** [comment]
I would guess that your secret key has duplicate characters. Could you
paste it in?

**Comment by aranw** [comment]
@zackkitzmiller my key is it was generated using the Laravel Command ```EVS6DRUtJ7Pxn2zAQfur5mlOoFMcseZy0a1q9kvNG4d3XIp8TiLhKwHYWjBbgC```

**Comment by zackkitzmiller** [comment]
@aranw that definitely seems like a bug. I'll investigate.

**Comment by jeteon** [comment]
I'm guessing that if the same ID occurs in two different tables, you would get the same Tiny ID for those IDs in both tables due to the consistency. I don't think its possible to guarantee the same Tiny ID won't pop up in both tables even if you used a difference key. Or is it that within one table that has unique IDs, there are duplicate strings popping up?

**Comment by zackkitzmiller** [comment]
Ha. That's actually exactly correct. I originally read this ticket wrong. 

Using the same secrecy key all identical integers will map to the same tiny.
